// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akmybjdzmlwjahhyvnsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFrbXliamR6bWx3amFoaHl2bnNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNjQ0MDUsImV4cCI6MjA3MDk0MDQwNX0.WxBTwRqowty9BHi2XjTL557SJ42gx13y5eg4S0stL14";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});